### ISSUE TITLE
index.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.es-es#1]
Incorrect pronoun concordance:

Current Translation (If its  a translation issue)
Para completar estos ejercicios, necesitará una suscripción a Microsoft Azure. Si su instructor no se le ha
proporcionado, puede registrarse para obtener una evaluación gratuita en https://azure.microsoft.com.

Suggested Translation (if it’s a translation issue)*
Para completar estos ejercicios, necesitará una suscripción a Microsoft Azure. Si su instructor no se la ha
proporcionado, puede registrarse para obtener una evaluación gratuita en https://azure.microsoft.com.

[index.md](https://github.com/MicrosoftLearning/AI-102-AIEngineer.es-es/files/7762025/index.md)

**Comment by olprod** [comment]
fixed.
![image](https://user-images.githubusercontent.com/16075726/149742459-065b1fc1-0439-440e-9bd8-4d646a0a8e4c.png)
