### ISSUE TITLE
Lab code and other files not present in this localized repository

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/AI-102-AIEngineer.es-es#10]
This repository lacks the per-lab folders which contain code and other supporting files used in each lab. Lab instructions direct the user to clone these files from the non-localized version of the lab, as in the line below.

https://github.com/MicrosoftLearning/AI-102-AIEngineer.es-es/blob/b2be17fefa0b217cf4d45495a755aa419b21c5ea/Instructions/01-get-started-cognitive-services.md?plain=1#L16

Adding the lab files to this repository and removing references to the non-localized repository would support a more complete and consistent localized learning experience.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
would have to be a call for the WWL PM

**Comment by stonezy123** [comment]
This is no translation issue with clone the source repo using code and other supporting files.
