### ISSUE TITLE
Labs 09b, 10b - Language Service not found in ES portal Marketplace

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/AI-102-AIEngineer.es-es#9]
In labs / learning paths 09b and 10b, the Language Service / Análisis de Texto resource type cannot be found in the Spanish-language (ES) Azure portal Marketplace using the name or search term provided in the instructions. The following are links to the ES and EN Marketplace pages for this resource type, for comparison.

https://portal.azure.com/?l=es.es-es#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/Microsoft.CognitiveServicesTextAnalytics
 
https://portal.azure.com/?l=en.en-us#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/Microsoft.CognitiveServicesTextAnalytics
 
This issue may be resolved by providing the correct "Análisis de texto" resource type name and a corresponding search term.

### LP 09b instructions
https://github.com/MicrosoftLearning/AI-102-AIEngineer.es-es/blob/b2be17fefa0b217cf4d45495a755aa419b21c5ea/Instructions/09b-language-understanding-(preview).md?plain=1#L26
 
> 2. Use el botón **&#65291;Crear un recurso**, busque *language* y cree un recurso del **servicio Language** con los valores siguientes:
 
Resource name: servicio Language
Search term: language
 
### LP 10b instructions
https://github.com/MicrosoftLearning/AI-102-AIEngineer.es-es/blob/b2be17fefa0b217cf4d45495a755aa419b21c5ea/Instructions/10b-language-understanding-client-(preview).md?plain=1#L31

> 2. Seleccione el botón **&#65291;Crear un recurso**, busque *servicio de lenguaje* y cree un recurso de **Language Service** con los valores siguientes: 

Resource name: Language Service
Search term: servicio de lenguaje
 
### Observed ES Azure portal behavior

Resource name: Análisis de texto
Search term (example): texto

**Comment by chriscarty00** [comment]
[Locfile](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7RXF1YWw7NTAzMDAuSW5zdHJ1Y3Rpb25zLjA5Yi1sYW5ndWFnZS11bmRlcnN0YW5kaW5nLShwcmV2aWV3KS5tZDwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtTcGFuaXNoPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d) to update

**Comment by chriscarty00** [comment]
Locfile updated
